sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  # google chrome standalone driver
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/chromedriver
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3

language: java
jdk:
 - oraclejdk8
notifications:
  email:
    recipients:
      - guilhermekelling@gmail.com
    on_success: always
    
    