sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: java
jdk:
 - oraclejdk8
notifications:
  email:
    recipients:
      - guilhermekelling@gmail.com
    on_success: always